import { getAuthSession } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import Link from "next/link";
import { redirect } from "next/navigation";
import ProjectCard from "@/components/ProjectCard";

export default async function ProjectsPage() {
  const session = await getAuthSession();

  if (!session?.user?.id) {
    redirect("/home");
  }

  const projects = await prisma.project.findMany({
    where: { userId: session.user.id },
    orderBy: { createdAt: 'desc' },
  });

  return (
    <div className="gallery-body">
      <div className="background-effects">
        <div className="blob blob-1"></div>
        <div className="blob blob-2" style={{ left: "60%", background: "var(--accent-primary)" }}></div>
      </div>



      <main className="gallery-main fade-in visible">
        <div className="gallery-header">
          <h1>My AI Generation History</h1>
          <p className="subtitle">All the sites generated by your profile. Publish them to the Community Board for others to use!</p>
          <div className="header-actions">
            <Link href="/builder" className="btn primary-btn">
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <line x1="12" y1="5" x2="12" y2="19"></line>
                <line x1="5" y1="12" x2="19" y2="12"></line>
              </svg>
              Build New Project
            </Link>
            <Link href="/community" className="btn secondary-btn">Browse Community</Link>
          </div>
        </div>

        {projects.length === 0 ? (
          <div className="error-banner">No generated websites found in your database. Go build something!</div>
        ) : (
          <div className="gallery-grid fade-in visible">
            {projects.map((project) => (
              <ProjectCard key={project.id} project={project} />
            ))}
          </div>
        )}
      </main>
    </div>
  );
}
